name: ssh-cloudflared-tunnel
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: CN-traveler/ssh-cloudflared-tunnel@1.0.0
        with:
          password: 123456
          token: ${{ secrets.SSH_TOKEN }}
