name: ssh
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          sudo echo -e "123456\n123456" | sudo passwd "root"
          sudo apt-get install -y openssh-server && \
          sudo echo "PermitRootLogin yes\nUsePAM no" > /etc/ssh/sshd_config.d/sshd.conf && \
          sudo cloudflared service install ${{ secrets.SSH_TOKEN }}
          sudo service ssh start
      - run: sudo tail -f /var/log/alternatives.log
