name: test-speed
on:
  workflow_dispatch:
jobs:
  test-speed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.1.1
      - run: |
          npm install --global fast-cli
          fast -u
