name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          repository: xHossein/PyPasser
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
      - run: |
          python3 ./setup.py install
          cd ./examples/reCaptchaV2/
          wget https://msedgedriver.azureedge.net/101.0.1210.53/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          mv msedgedriver msedgedriver.exe
          ls
          pwd
          python3 ./demo.py
