name: v2ray-ws-tls-cloudflared-tunnel
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 6 * * *"
    - cron: "0 12 * * *"
    - cron: "0 18 * * *"
jobs:
  workflow_dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: CN-traveler/v2ray-ws-tls-cloudflared-tunnel@2.0.0
        with:
          id: '62268a5f-31b6-45d0-8acc-6cee62d7a554'
          path: '/cloudflared-tunnel'
          token: '${{ secrets.TOKEN }}'
  time0:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 * * *'
    steps:
      - uses: CN-traveler/v2ray-ws-tls-cloudflared-tunnel@2.0.0
        with:
          id: '62268a5f-31b6-45d0-8acc-6cee62d7a554'
          path: '/cloudflared-tunnel'
          token: '${{ secrets.TOKEN }}'
  time6:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 6 * * *'
    steps:
      - uses: CN-traveler/v2ray-ws-tls-cloudflared-tunnel@2.0.0
        with:
          id: '62268a5f-31b6-45d0-8acc-6cee62d7a554'
          path: '/cloudflared-tunnel'
          token: '${{ secrets.TOKEN }}'
  time12:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 12 * * *'
    steps:
      - uses: CN-traveler/v2ray-ws-tls-cloudflared-tunnel@2.0.0
        with:
          id: '62268a5f-31b6-45d0-8acc-6cee62d7a554'
          path: '/cloudflared-tunnel'
          token: '${{ secrets.TOKEN }}'
  time18:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 18 * * *'
    steps:
      - uses: CN-traveler/v2ray-ws-tls-cloudflared-tunnel@2.0.0
        with:
          id: '62268a5f-31b6-45d0-8acc-6cee62d7a554'
          path: '/cloudflared-tunnel'
          token: '${{ secrets.TOKEN }}'
